version: '3.3'

volumes:
  sqlite_data:
  static:

services:
  django:
    build: .
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=recipe_project.settings
  nginx:
    build: ./nginx/
    volumes:
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django