# Generated by Django 4.2.16 on 2024-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0003_recipeingredient_unique_recipes_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
