# Generated by Django 4.2.16 on 2024-11-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_recipe_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name',), name='recipe_catalog_recipe_name_unique'),
        ),
    ]
