# Generated by Django 4.2.16 on 2024-11-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0005_recipe_recipe_catalog_recipe_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
