# Generated by Django 4.2.16 on 2024-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0006_recipeingredient_count_recipeingredient_weight'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name',), name='recipe_catalog_ingredient_name_unique'),
        ),
    ]
