# Generated by Django 4.2.16 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0007_ingredient_recipe_catalog_ingredient_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='описание', max_length=1000),
        ),
    ]
